[tool.ruff]
# Enable flake8-compatibility
line-length = 88
target-version = "py310"
select = ["E", "F", "W", "I", "B", "C4", "ARG", "SIM"]
# Игнорируем часто встречающиеся ошибки в коде FastAPI
ignore = [
    "B008",  # Вызов функций в аргументах по умолчанию (стандартный паттерн FastAPI)
    "E501",  # Длинные строки (можно постепенно исправить)
    "ARG001"  # Неиспользуемые аргументы (часто нужны для совместимости API)
]

# Allow autofix for all enabled rules (when `--fix` is provided)
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories
exclude = [
    ".git",
    ".ruff_cache",
    "__pycache__",
    "venv",
    ".env",
    ".venv",
    "env",
    "migrations"
]

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.isort]
known-third-party = ["fastapi", "pydantic", "sqlalchemy"]