name: Deploy RHCSA Testing Service

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    # Запускаем только для мержа в main или прямого пуша в main
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to remote VM
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.VM_HOST }} "
            cd ${{ secrets.PROJECT_PATH }} &&
            git pull origin main &&
            sudo docker compose down &&
            sudo docker compose up -d --build
          "
      
      - name: Verify deployment
        run: |
          echo "Deployment completed successfully!"
          echo "Application should be available at http://${{ secrets.VM_HOST }}:8000" 